insert into TB_PEDIDO(ID_TIPO_PEDIDO,DT_PEDIDO,NR_PEDIDO,ID_CLIENTE,ID_FORNECEDOR,ID_FILIAL,VL_TOTAL_PEDIDO) values(1,date_format(current_date(), '%d/%m/%Y'),101,1,1,1,50);

insert into TB_PEDIDO(ID_TIPO_PEDIDO,DT_PEDIDO,NR_PEDIDO,ID_CLIENTE,ID_FORNECEDOR,ID_FILIAL,VL_TOTAL_PEDIDO) values(2,date_format(current_date(), '%d/%m/%Y'),102,2,1,1,30);

insert into TB_PEDIDO_ITEM(ID_PEDIDO,NR_PEDIDO_ITEM,ID_PRODUTO,QT_ITEM,VL_UNITARIO) values(1,1,1,5,10);

insert into TB_PEDIDO_ITEM(ID_PEDIDO,NR_PEDIDO_ITEM,ID_PRODUTO,QT_ITEM,VL_UNITARIO) values(2,2,1,2,15);

insert into TB_NF(ID_TIPO_OPERACAO,ID_STATUS_NOTA,DT_EMISSAO,NR_NOTA,ID_CLIENTE,ID_FORNECEDOR,ID_FILIAL,ID_TIPO_PAGAMENTO,VL_TOTAL_NOTA) values(1,3,date_format(current_date(), '%d/%m/%Y'),101,1,1,1,3,50);

insert into TB_NF(ID_TIPO_OPERACAO,ID_STATUS_NOTA,DT_EMISSAO,NR_NOTA,ID_CLIENTE,ID_FORNECEDOR,ID_FILIAL,ID_TIPO_PAGAMENTO,VL_TOTAL_NOTA) values(2,3,date_format(current_date(), '%d/%m/%Y'),102,2,1,1,2,30);

update TB_ESTOQUE set QT_ESTOQUE_DISPONIVEL=5 WHERE ID_FILIAL=1 AND ID_PRODUTO=1;

update TB_ESTOQUE set QT_ESTOQUE_DISPONIVEL=2 WHERE ID_FILIAL=1 AND ID_PRODUTO=1;

